version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - TZ=Asia/Kolkata
    container_name: server
    working_dir: /home/apps/prog-img/
    volumes:
      - ~/Developer/Projects/Node/prog-img:/home/apps/prog-img
      - node_modules:/home/apps/prog-img/node_modules
    depends_on:
      mongo_db:
        condition: service_healthy
      redis_db:
        condition: service_started
      redis-commander:
        condition: service_started
    command: npm start

  mongo_db:
    image: mongo:5.0.8
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - ~/Developer/dbs/mongo:/data/db
    command: --quiet --logpath /dev/null
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/healthcheck-database --quiet

  redis_db:
    image: redis:7.0.0
    container_name: redis_db
    volumes:
      - ~/Developer/dbs/redis:/data
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:redis_db:6379
    container_name: redis-commander
    ports:
      - 8081:8081
    depends_on:
      redis_db:
        condition: service_started

volumes:
  node_modules:
