version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    container_name: server
    working_dir: /app
    volumes:
      - ~/Developer/Projects/Node/prog-img:/app
      - node_modules:/app/node_modules
    depends_on:
      redis_db:
        condition: service_started
      redis-commander:
        condition: service_started
    command: npm start

  redis_db:
    image: redis:7.0.0
    container_name: redis_db
    volumes:
      - ~/Developer/dbs/redis:/data
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:redis_db:6379
    container_name: redis-commander
    ports:
      - 8081:8081
    depends_on:
      redis_db:
        condition: service_started

volumes:
  node_modules:
